apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: authors-split
spec:
  service: authors
  backends:
  - service: authors
    weight: 900m
  - service: authors-clone
    weight: 100m
